version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - zip -r code.zip .
  post_build:
    finally:
      - aws lambda update-function-code --function-name webpage_consulting_calendar --zip-file fileb://./code.zip
